[android] work around deprecated APIs
Context: https://developer.android.com/reference/android/content/pm/PackageManager#getPackageInfo(java.lang.String,%20int)

Fixes the error:

    src/Essentials/src/AppInfo/AppInfo.android.cs(16,80): error CS0618: 'PackageManager.GetPackageInfo(string, PackageInfoFlags)' is obsolete: 'deprecated'
    src/Essentials/src/Permissions/Permissions.android.cs(19,22): error CS0618: 'PackageManager.GetPackageInfo(string, PackageInfoFlags)' is obsolete: 'deprecated'

We can't use the new API either, because it was added in API 33.